version: '3'
services:
  app:
    build: .
    ports:
      - '3096:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    networks:
      - bridge
networks:
  bridge:
    driver: bridge